import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));const pub=path.join(root,'public');const data=path.join(root,'uoc-nguyen');fs.mkdirSync(data,{recursive:true});const dbFile=path.join(data,'wishes.json');
const COOKIE='nguyet_device_local';
const read=()=>{try{return JSON.parse(fs.readFileSync(dbFile,'utf8'))}catch{return[]}};
const write=a=>{fs.writeFileSync(dbFile,JSON.stringify(a,null,2),'utf8');const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';fs.writeFileSync(path.join(data,'uoc-nguyen.csv'),'\uFEFFSTT,Thời gian,Tên / thiết bị,Ước nguyện\r\n'+a.map((w,i)=>[i+1,w.created_at,w.sender_name||'Ẩn danh',w.message].map(q).join(',')).join('\r\n'),'utf8');fs.writeFileSync(path.join(data,'uoc-nguyen.txt'),a.map((w,i)=>`${i+1}. [${w.created_at}] ${w.sender_name||'Ẩn danh'} | ${w.message}`).join('\n'),'utf8')};
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.mp3':'audio/mpeg','.svg':'image/svg+xml'};
const cookies=req=>Object.fromEntries((req.headers.cookie||'').split(';').map(v=>v.trim()).filter(Boolean).map(v=>{const i=v.indexOf('=');return i<0?[v,'']:[v.slice(0,i),decodeURIComponent(v.slice(i+1))]}));
const device=req=>{let token=cookies(req)[COOKIE],fresh=false;if(!token){token=crypto.randomUUID()+'-'+crypto.randomUUID();fresh=true}const hash=crypto.createHash('sha256').update(token).digest('hex');return{token,hash,fresh}};
const setCookie=(res,d)=>{if(d.fresh)res.setHeader('set-cookie',`${COOKIE}=${encodeURIComponent(d.token)}; Path=/; Max-Age=31536000; HttpOnly; SameSite=Lax`)};
const sendJson=(res,data,status=200)=>{res.statusCode=status;res.setHeader('content-type','application/json; charset=utf-8');res.setHeader('cache-control','no-store');res.end(JSON.stringify(data))};
http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');
  if(u.pathname==='/api/wishes/mine'&&req.method==='GET'){const d=device(req);setCookie(res,d);const limit=Math.max(1,Math.min(Number(u.searchParams.get('limit'))||200,500));return sendJson(res,{wishes:read().filter(w=>w.device_hash===d.hash).slice(0,limit)})}
  if(u.pathname==='/api/wishes/count'&&req.method==='GET'){const d=device(req);setCookie(res,d);return sendJson(res,{count:read().length})}
  if(u.pathname==='/api/wishes'&&req.method==='POST'){const d=device(req);setCookie(res,d);let b='';req.on('data',x=>b+=x);req.on('end',()=>{try{const body=JSON.parse(b);const sender_name=String(body.sender_name||body.senderName||'').trim().normalize('NFC')||'Ẩn danh';const m=String(body.message||'').trim().normalize('NFC');if(sender_name.length>60||!m||m.length>160)return sendJson(res,{error:'Dữ liệu không hợp lệ'},400);const a=read();const w={id:Date.now(),device_hash:d.hash,sender_name,message:m,created_at:new Date().toISOString()};a.unshift(w);write(a.slice(0,1000));sendJson(res,{ok:true,wish:{id:w.id,sender_name,message:m,created_at:w.created_at}},201)}catch{return sendJson(res,{error:'JSON không hợp lệ'},400)}});return}
  if(u.pathname==='/api/wishes/mine.csv'&&req.method==='GET'){const d=device(req);setCookie(res,d);const items=read().filter(w=>w.device_hash===d.hash);const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';const csv='\uFEFFSTT,Thời gian,Tên / thiết bị,Ước nguyện\r\n'+items.map((w,i)=>[i+1,w.created_at,w.sender_name||'Ẩn danh',w.message].map(q).join(',')).join('\r\n');res.setHeader('content-type','text/csv; charset=utf-8');res.setHeader('content-disposition','attachment; filename="uoc-nguyen-cua-toi.csv"');return res.end(csv)}
  if((u.pathname==='/api/wishes'||u.pathname==='/api/wishes.csv')&&req.method==='GET')return sendJson(res,{error:'Danh sách ước nguyện chung không công khai'},403);
  let p=path.join(pub,u.pathname==='/'?'index.html':decodeURIComponent(u.pathname).replace(/^\//,''));if(!p.startsWith(pub)||!fs.existsSync(p)||fs.statSync(p).isDirectory()){res.statusCode=404;return res.end('Not found')}res.setHeader('content-type',mime[path.extname(p)]||'application/octet-stream');fs.createReadStream(p).pipe(res)
}).listen(8787,()=>console.log('http://localhost:8787'));
